### ISSUE TITLE
How can we test other images

### ISSUE THREAD

**Issue by Vishal2188** [trevor-m/tensorflow-SRGAN#2]
I want to test other images using checkpoints of training process. How can I do this

**Comment by trevor-m** [comment]
To test on other images, you can put them in a new folder in the Benchmarks directory. Make sure each image ends in '_HR.png'.

Then, modify line 53 of train.py to include your new image set, like so:
```
benchmarks = [Benchmark('Benchmarks/Set5', name='Set5'),
                Benchmark('Benchmarks/Set14', name='Set14'),
                Benchmark('Benchmarks/BSD100', name='BSD100'),
                Benchmark('Benchmarks/MyImageSet', name='MyImageSet')]
```
where 'MyImageSet' is the name of the folder you created

You can then run train.py using the same arguments as when you trained you model, except now adding the argument: `--load results/<experiment name>/weights-<iteration number>`.

**Comment by Vishal2188** [comment]
Thanks a lot for helping me.

WIth Regards

Mr. Vishal M. Chudasama
