### ISSUE TITLE
No of Training parameter

### ISSUE THREAD

**Issue by Vishal2188** [trevor-m/tensorflow-SRGAN#6]
Does it possible to calculate number of trainable parameters (not manually)?

**Comment by trevor-m** [comment]
Something like `np.sum([np.prod(v.get_shape().as_list()) for v in tf.trainable_variables()])` could work (from https://stackoverflow.com/questions/38160940/how-to-count-total-number-of-trainable-parameters-in-a-tensorflow-model)
